<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TicketingSystem.Domain</RootNamespace>
    <AssemblyName>TicketingSystem.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR.Contracts" />
    <PackageReference Include="MessagePack" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

</Project>
